"use client";

import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

const locales = {
  zh: {
    siteTitle: "知忆",
    records: "记录",
    detail: "详情",
    records_suffix: "records",
    noRecords: "暂无记录",
    cancel: "取消",
    delete: "删除",
    preview: "预览",
    hidePreview: "隐藏预览",
    closePreview: "关闭预览",
    back: "返回",
    prevLabel: "上一篇",
    nextLabel: "下一篇",
    prevPage: "上一页",
    nextPage: "下一页",
    deleted: "已删除",
    updated: "已更新",
    published: "已发布",
    all: "全部",
    switchLang: "English",
    settings: "设置",
    settingsDesc: "配置数据库连接，可切换 Turso 或自部署 sqld 服务器",
    settingsDb: "数据库",
    settingsDbUrl: "数据库地址",
    settingsDbToken: "认证 Token",
    settingsSave: "保存",
    settingsClear: "清除",
    settingsHint1: "💡 配置后刷新页面生效。未配置时使用默认存储（本地 fs / GitHub API）。",
    settingsHint2: "🔄 自部署 sqld 的用户，填入你的服务器地址和 token 即可切换。",
    settingsAbout: "关于架构",
    settingsArch: "当前架构：",
    settingsBackup: "版本备份",
    settingsNote: "知忆采用 Turso 主存储 + GitHub 备份的双层架构。Web 和 CLI 均直连 Turso，无需经过应用层中转。",
    leftPanelTitle: "文件树",
    leftPanelUpload: "上传文件夹",
    leftPanelFiles: "文件",
    leftPanelView: "视图",
    leftPanelViewList: "列表",
    leftPanelViewGrid: "网格",
    leftPanelViewCompact: "紧凑",
    leftPanelFilter: "筛选",
    leftPanelSearch: "搜索知识...",
    leftPanelClose: "收起面板",
    navPrivateList: "私有",
    navPublicList: "公开",
    navFilesSkills: "文件",
    navImportArticle: "导入",
    navLogin: "登录",
    navLogout: "退出",
    navEditUsername: "修改用户名",
    usernameDialogTitle: "修改用户名",
    usernameLabel: "用户名",
    usernamePlaceholder: "请输入用户名",
    usernameEmptyError: "用户名不能为空",
    usernameSaving: "保存中...",
    usernameSaveBtn: "保存",
    loginRequired: "请先登录",
    navSettings: "设置",
    agentTitle: "AI 助手",
    agentCollapse: "收起",
    agentExpand: "展开",
    agentWelcome: "你好！我是你的知识助手。我可以帮你：",
    agentFeature1: "总结当前文章",
    agentFeature2: "回答知识库问题",
    agentFeature3: "推荐相关文章",
    agentFeature4: "生成综合报告",
    agentPlaceholder: "向知识库提问...",
    agentSend: "发送",
    agentHint: "Agent 功能开发中，敬请期待",
    agentSessions: "对话列表",
    agentNewSession: "新对话",
    agentNotConfigured: "**Agent 未配置**\n\n请在左侧设置中填入 LLM API Key 和 Base URL。\n\n点击左下角齿轮图标打开设置 → Agent 标签页。",
    agentAuthFailed: "**认证失败**\n\nAPI Key 无效，请在设置中检查。",
    agentConnectionFailed: "**连接失败**\n\n无法连接到 LLM 服务，请检查 Base URL 是否正确。",
    agentToolRunning: "正在执行: {name}...",
    agentToolFailed: "工具 {name} 执行失败",
    agentUsingTool: "Using tool: {name}...",
    agentWaitingForResponse: "正在生成回复...",
    agentUnknownError: "未知错误",
    agentNoContent: "LLM 服务未返回内容，请检查 API Key 和 Base URL 是否正确。",
    agentNetworkError: "网络错误: {message}",
    agentDisclaimer: "内容由 AI 生成，仅供参考",
    agentClearConversation: "清除对话",
    agentClickAgain: "再次点击确认清除",
    agentClickAgainConfirm: "再次点击确认",
    agentCopyMessage: "复制消息",
    agentSources: "来源",
    loginTitle: "登录",
    loginAccount: "账号",
    loginEmail: "邮箱",
    loginPassword: "密码",
    loginBtn: "登录",
    loggingIn: "登录中...",
    loginErrorEmpty: "请填写所有字段",
    loginErrorFailed: "登录失败",
    loginErrorNetwork: "网络错误，请重试",
    loginOrRegister: "没有账号？去注册",
    registerTitle: "注册",
    registerBtn: "注册",
    registering: "注册中...",
    registerOrLogin: "已有账号？去登录",
    sendCode: "发送验证码",
    sendingCode: "发送中...",
    codeSent: "已发送",
    codePlaceholder: "请输入验证码",
    sliderCaptcha: "请先滑动验证",
    sliderHint: "→ 向右滑动验证 ←",
    sliderOk: "✓ 验证通过",
    passwordMinLength: "密码至少 6 位",
    emailPlaceholder: "请输入邮箱",
    passwordPlaceholder: "请输入密码",
    loginUsername: "用户名",
    settingsTitle: "设置",
    settingsTheme: "主题",
    settingsLight: "浅色",
    settingsDark: "深色",
    settingsSystem: "跟随系统",
    settingsAgent: "Agent",
    settingsBaseUrl: "Base URL",
    settingsApiKey: "API Key",
    settingsModel: "Model",
    settingsSaveBtn: "保存",
    settingsSaving: "保存中...",
    settingsConfigured: "已配置",
    settingsVectorSearch: "向量搜索",
    settingsVectorSearchDisabled: "当前部署环境不支持向量数据库，已禁用该功能。",
    settingsZvec: "Zvec",
    settingsZvecTooltip: "当前使用内存索引，重启后数据丢失。开启 Zvec 可启用嵌入式向量数据库持久化存储。",
    settingsEmbeddingModel: "Embedding Model",
    settingsApiKeyClickHint: "（点击输入新密钥）",
    searchSemanticPlaceholder: "语义搜索...",
    searchKeywordPlaceholder: "按标题、摘要或分类搜索...",
    searchSwitchSemantic: "Switch to semantic search",
    searchSwitchKeyword: "Switch to keyword search",
    searchNoSemanticMatch: "No semantic matches for \"{query}\"",
    searchNoKeywordMatch: "No records matching \"{query}\"",
    recordsFormatMD: "MD",
    recordsFormatHTML: "HTML",
    recordsVisibilityPublic: "Public",
    recordsVisibilityPrivate: "Private",
    prev: "PREV",
    next: "NEXT",
    importTitle: "导入文章",
    importUrlTab: "URL",
    importRssTab: "RSS Feed",
    importUrlDesc: "输入文章 URL，抓取并导入为知识记录。",
    importRssDesc: "输入 RSS 订阅地址，浏览并选择文章。",
    importFetchPreview: "抓取并预览",
    importBrowseFeed: "浏览订阅",
    importFetching: "获取中...",
    importPreview: "预览",
    importImages: "张图片",
    importCategory: "分类",
    importBack: "返回",
    importImport: "导入",
    importImporting: "导入中...",
    importArticles: "篇文章",
    importSelectAll: "全选",
    importSucceeded: "个成功",
    importFailed: "个失败",
    importPrivateHint: "当前导入文章默认为私有，如需公开请在导入后修改可见性",
    slashNoCommands: "No matching commands",
    slashCommands: "Commands",
    slashSkills: "Skills",
    detailSimilarTitle: "相关文章",
    detailContents: "目录",
    uploadTitle: "上传文件夹",
    uploadSelectDesc: "选择包含 .md 文件的文件夹",
    uploadSelectHint: "文件夹名将自动识别为分类，.md 文件名将作为标题。支持嵌套文件夹。",
    uploadSelectBtn: "选择文件夹",
    uploadFound: "找到",
    uploadFiles: "个文件",
    uploadTitlePlaceholder: "标题",
    uploadImages: "张图片",
    uploadImport: "导入",
    uploadProgress: "导入中",
    uploadDone: "导入完成",
    uploadSuccess: "个成功",
    uploadFailed: "个失败",
    noMdFiles: "所选文件夹中没有找到 .md 文件",
    confirmDeleteTitle: "删除确认",
    confirmDeleteMessage: "确定要删除此记录吗？此操作不可撤销。",
    deleting: "删除中...",
    close: "关闭",
    footerCopyright: "© 2026 知忆",
  },
  en: {
    siteTitle: "Anamnesis",
    records: "Records",
    detail: "Detail",
    records_suffix: "records",
    noRecords: "No records yet",
    cancel: "Cancel",
    delete: "Delete",
    preview: "Preview",
    hidePreview: "Hide Preview",
    closePreview: "Close Preview",
    back: "BACK",
    prevLabel: "Prev",
    nextLabel: "Next",
    prevPage: "Prev Page",
    nextPage: "Next Page",
    deleted: "Deleted",
    updated: "Updated",
    published: "Published",
    all: "All",
    switchLang: "中文",
    settings: "Settings",
    settingsDesc: "Configure database connection — switch between Turso and self-hosted sqld",
    settingsDb: "Database",
    settingsDbUrl: "Database URL",
    settingsDbToken: "Auth Token",
    settingsSave: "Save",
    settingsClear: "Clear",
    settingsHint1: "💡 Changes apply on next page load. Falls back to local fs / GitHub API when unset.",
    settingsHint2: "🔄 Self-host sqld users: point to your server address and token.",
    settingsAbout: "Architecture",
    settingsArch: "Current architecture:",
    settingsBackup: "version backup",
    settingsNote: "Zhiyi uses Turso as primary storage with GitHub backup. Both Web and CLI connect directly to Turso via HTTP.",
    leftPanelTitle: "File Tree",
    leftPanelUpload: "Upload Folder",
    leftPanelFiles: "Files",
    leftPanelView: "View",
    leftPanelViewList: "List",
    leftPanelViewGrid: "Grid",
    leftPanelViewCompact: "Compact",
    leftPanelFilter: "Filter",
    leftPanelSearch: "Search knowledge...",
    leftPanelClose: "Close Panel",
    agentTitle: "AI Assistant",
    agentCollapse: "Collapse",
    agentExpand: "Expand",
    agentWelcome: "Hi! I'm your knowledge assistant. I can help you:",
    agentFeature1: "Summarize current article",
    agentFeature2: "Answer knowledge base questions",
    agentFeature3: "Recommend related articles",
    agentFeature4: "Generate comprehensive reports",
    agentPlaceholder: "Ask your knowledge base...",
    agentSend: "Send",
    agentHint: "Agent features coming soon",
    agentSessions: "Sessions",
    agentNewSession: "New conversation",
    agentNotConfigured: "**Agent not configured**\n\nSet LLM API Key and Base URL in settings on the left.\n\nClick the gear icon at the bottom left → Agent tab.",
    agentAuthFailed: "**Authentication failed**\n\nAPI Key invalid, please check in settings.",
    agentConnectionFailed: "**Connection failed**\n\nCannot connect to LLM service, please check Base URL.",
    agentToolRunning: "Running: {name}...",
    agentToolFailed: "Tool {name} failed",
    agentUsingTool: "Using tool: {name}...",
    agentWaitingForResponse: "Generating response...",
    agentUnknownError: "Unknown error",
    agentNoContent: "LLM service returned no content, please check API Key and Base URL.",
    agentNetworkError: "Network error: {message}",
    agentDisclaimer: "Content generated by AI, for reference only",
    agentClearConversation: "Clear conversation",
    agentClickAgain: "Click again to clear",
    agentClickAgainConfirm: "Click again to confirm",
    agentCopyMessage: "Copy message",
    agentSources: "Sources",
    loginTitle: "Login",
    loginAccount: "Account",
    loginEmail: "Email",
    loginPassword: "Password",
    loginRequired: "Login required",
    navEditUsername: "Edit Username",
    usernameDialogTitle: "Edit Username",
    usernameLabel: "Username",
    usernamePlaceholder: "Enter username",
    usernameEmptyError: "Username cannot be empty",
    usernameSaving: "Saving...",
    usernameSaveBtn: "Save",
    loginBtn: "Login",
    loggingIn: "Logging in...",
    loginErrorEmpty: "Please fill all fields",
    loginErrorFailed: "Login failed",
    loginErrorNetwork: "Network error, please retry",
    loginOrRegister: "No account? Register",
    registerTitle: "Register",
    registerBtn: "Register",
    registering: "Registering...",
    registerOrLogin: "Already have an account? Login",
    sendCode: "Send Code",
    sendingCode: "Sending...",
    codeSent: "Sent",
    codePlaceholder: "Enter verification code",
    sliderCaptcha: "Please verify first",
    sliderHint: "→ Slide to verify ←",
    sliderOk: "✓ Verified",
    passwordMinLength: "Password must be at least 6 characters",
    emailPlaceholder: "Enter email",
    passwordPlaceholder: "Enter password",
    loginUsername: "Username",
    settingsTitle: "Settings",
    settingsTheme: "Theme",
    settingsLight: "Light",
    settingsDark: "Dark",
    settingsSystem: "System",
    settingsAgent: "Agent",
    settingsBaseUrl: "Base URL",
    settingsApiKey: "API Key",
    settingsModel: "Model",
    settingsSaveBtn: "Save",
    settingsSaving: "Saving...",
    settingsConfigured: "Configured",
    settingsVectorSearch: "Vector Search",
    settingsVectorSearchDisabled: "Vector database is not available in this deployment and has been disabled.",
    settingsZvec: "Zvec",
    settingsZvecTooltip: "Currently using in-memory index, data lost on restart. Enable Zvec for persistent embedded vector database.",
    settingsEmbeddingModel: "Embedding Model",
    settingsApiKeyClickHint: " (click to enter new key)",
    searchSemanticPlaceholder: "Semantic search by meaning...",
    searchKeywordPlaceholder: "Search by title, summary, or category...",
    searchSwitchSemantic: "Switch to semantic search",
    searchSwitchKeyword: "Switch to keyword search",
    searchNoSemanticMatch: "No semantic matches for \"{query}\"",
    searchNoKeywordMatch: "No records matching \"{query}\"",
    recordsFormatMD: "MD",
    recordsFormatHTML: "HTML",
    recordsVisibilityPublic: "Public",
    recordsVisibilityPrivate: "Private",
    prev: "PREV",
    next: "NEXT",
    importTitle: "Import Article",
    importUrlTab: "URL",
    importRssTab: "RSS Feed",
    importUrlDesc: "Enter a URL to fetch and import as a knowledge record.",
    importRssDesc: "Enter an RSS feed URL to browse and select articles.",
    importFetchPreview: "Fetch & Preview",
    importBrowseFeed: "Browse Feed",
    importFetching: "Fetching...",
    importPreview: "Preview",
    importImages: "images",
    importCategory: "Category",
    importBack: "Back",
    importImport: "Import",
    importImporting: "Importing...",
    importArticles: "articles",
    importSelectAll: "Select All",
    importSucceeded: "succeeded",
    importFailed: "failed",
    importPrivateHint: "Imported articles default to private. Change visibility after import if public is needed.",
    slashNoCommands: "No matching commands",
    slashCommands: "Commands",
    slashSkills: "Skills",
    detailSimilarTitle: "Similar Articles",
    detailContents: "Contents",
    confirmDeleteTitle: "Delete Confirmation",
    confirmDeleteMessage: "Are you sure you want to delete this record? This action cannot be undone.",
    deleting: "Deleting...",
    noMdFiles: "No .md files found in the selected folder",
    uploadSelectDesc: "Select a folder containing .md files",
    uploadSelectHint: "Folder name is auto-detected as category, .md filenames become titles. Nested folders supported.",
    uploadSelectBtn: "Select Folder",
    uploadFound: "Found",
    uploadFiles: "files",
    uploadTitlePlaceholder: "Title",
    uploadImages: "images",
    uploadImport: "Import",
    uploadProgress: "Importing",
    uploadDone: "Import complete",
    uploadSuccess: "succeeded",
    uploadFailed: "failed",
    close: "Close",
    footerCopyright: "© 2026 Zhiyi",
  },
};

type Lang = "zh" | "en";

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

function lookup(key: string, lang: Lang): string {
  const keys = key.split(".");
  let obj: Record<string, unknown> = locales[lang] || locales.zh;
  for (const k of keys) {
    if (obj && typeof obj === "object" && k in obj) {
      obj = obj[k] as Record<string, unknown>;
    } else {
      return key;
    }
  }
  return typeof obj === "string" ? obj : key;
}

const LangContext = createContext<LangContextValue>({
  lang: "zh",
  setLang: () => {},
  t: (key: string) => lookup(key, "zh"),
});

export function useLanguage() {
  return useContext(LangContext);
}

export function LanguageProvider({
  children,
  initialLang = "zh",
}: {
  children: ReactNode;
  initialLang?: Lang;
}) {
  const [lang, setLangState] = useState<Lang>(initialLang);

  useEffect(() => {
    const saved = localStorage.getItem("kb-lang") as Lang | null;
    if (saved && saved !== initialLang && (saved === "en" || saved === "zh")) {
      setLangState(saved);
    }
  }, [initialLang]);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("kb-lang", l);
    try {
      document.cookie = `kb-lang=${l};path=/;max-age=31536000`;
    } catch {}
  }

  function t(key: string): string {
    return lookup(key, lang);
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}